#ifndef FLOWMETER_H
#define FLOWMETER_H

#include "STD_TYPES.h"

/* Number of pulses generated by the flowmeter for one liter */
#define FLOWMETER_PULSES_PER_LITER 450UL

/* Initialize Flowmeter */
STD_ReturnType FLOWMETER_Init(void);

/* Start a new measurement */
STD_ReturnType FLOWMETER_StartMeasurement(void);

/* Get number of received pulses */
STD_ReturnType FLOWMETER_GetPulseCount(uint16 *Copy_pu16PulseCount);

/* Convert pulses to liters */
STD_ReturnType FLOWMETER_GetLiters(uint16 *Copy_pu16Liters);

/* Reset current measurement */
STD_ReturnType FLOWMETER_ResetMeasurement(void);

#endif /* FLOWMETER_H */